openapi: 3.0.2
info:
  title: Fast API
  version: 0.1.0
paths:
  /must_error:
    post:
      summary: Must Error
      operationId: must_error_must_error_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandOutput'
components:
  schemas:
    CommandOutput:
      title: CommandOutput
      required:
      - console
      - duration
      type: object
      properties:
        status_code:
          title: Status Code
          type: integer
          default: 0
        console:
          title: Console
          type: array
          items:
            $ref: '#/components/schemas/_OutputRow'
        duration:
          title: Duration
          type: number
    _OutputRow:
      title: _OutputRow
      required:
      - port
      - lines
      type: object
      properties:
        port:
          title: Port
          type: string
        lines:
          title: Lines
          type: array
          items:
            type: string
