# this module is generated by monogusa.web.codegen
import commands
from fastapi import (
    Depends,
    APIRouter,
    FastAPI,
)
import typing as t
from pydantic import BaseModel
from monogusa.web import runtime


router = APIRouter()


class HelloInput(BaseModel):
    name: str
    nickname: t.Optional[str] = None


@router.post("/hello", response_model=runtime.CommandOutput)
def hello(input: HelloInput) -> t.Dict[str, t.Any]:
    with runtime.handle() as s:
        commands.hello(**input.dict())
    return s.dict()


def main(app: FastAPI):
    from monogusa.web import cli

    cli.run(app)


app = FastAPI()
app.include_router(router)


if __name__ == "__main__":
    main(app=app)
