openapi: 3.0.2
info:
  title: Fast API
  version: 0.1.0
paths:
  /hello:
    post:
      summary: Hello
      operationId: hello_hello_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HelloInput'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandOutput'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /bye:
    post:
      summary: Bye
      operationId: bye_bye_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ByeInput'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandOutput'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ByeInput:
      title: ByeInput
      required:
      - name
      type: object
      properties:
        name:
          title: Name
          type: string
    CommandOutput:
      title: CommandOutput
      required:
      - stdout
      - stderr
      - duration
      type: object
      properties:
        stdout:
          title: Stdout
          anyOf:
          - type: array
            items:
              type: string
          - type: string
        stderr:
          title: Stderr
          anyOf:
          - type: array
            items:
              type: string
          - type: string
        duration:
          title: Duration
          type: number
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    HelloInput:
      title: HelloInput
      required:
      - name
      type: object
      properties:
        name:
          title: Name
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
