openapi: 3.0.2
info:
  title: Fast API
  version: 0.1.0
paths:
  /hello:
    post:
      summary: Hello
      operationId: hello_hello_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HelloInput'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandOutput'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    CommandOutput:
      title: CommandOutput
      required:
      - console
      - duration
      type: object
      properties:
        status_code:
          title: Status Code
          type: integer
          default: 0
        console:
          title: Console
          type: array
          items:
            $ref: '#/components/schemas/_OutputRow'
        duration:
          title: Duration
          type: number
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    HelloInput:
      title: HelloInput
      required:
      - name
      type: object
      properties:
        name:
          title: Name
          type: string
        nickname:
          title: Nickname
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    _OutputRow:
      title: _OutputRow
      required:
      - port
      - lines
      type: object
      properties:
        port:
          title: Port
          type: string
        lines:
          title: Lines
          type: array
          items:
            type: string
